/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 */

import org.gradle.api.tasks.bundling.Jar

// group = "org.bd"
// version = "1.0.0"

group = "co.gongzh.procbridge"
// group = "co.gongzh.procbridge"
version = "2.1.0-gradle"
description = "procbridge"
// sourceCompatibility = "1.8"

val sourcesJar by tasks.registering(Jar::class) {
    classifier = "sources"
//    sourceSets.main.get().java.srcDir("src")
    from(sourceSets.main.get().allSource)
}

plugins {
    // Apply the Kotlin JVM plugin to add support for Kotlin on the JVM
    id("org.jetbrains.kotlin.jvm").version("1.3.10")
    `java`
    `maven-publish`

    // Apply the application to add support for building a CLI application
    // application
}

repositories {
    // Use jcenter for resolving your dependencies.
    // You can declare any Maven/Ivy/file repository here.
    mavenLocal()
    maven ( uri ( "http://repo.maven.apache.org/maven2" ) )
    jcenter()
}

dependencies {
    // Use the Kotlin JDK 8 standard library
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // Use the Kotlin test library
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    compile ("com.google.code.gson:gson:2.7")
    compile ("org.jetbrains:annotations:15.0")
    compile ("org.slf4j:slf4j-api:1.7.25")
    testCompile ("junit:junit:4.12")
    testCompile ("ch.qos.logback:logback-classic:1.2.3")
}

publishing {
    repositories {
        maven {
            // change to point to your repo, e.g. http://my.org/repo
            url = uri("$buildDir/repo")
        }
    }
    publications {
        register("procbridge", MavenPublication::class) {
            from(components["java"])
            artifact(sourcesJar.get())
        }
    }
}

